[App]
Name = "ai.h2o.wave.sql-sidekick"
Title = "SQL-Sidekick"
Description = "QnA with tabular data using NLQ"
LongDescription = "about.md"
InstanceLifecycle = "MANAGED"
Tags = ["DATA_SCIENCE", "MACHINE_LEARNING", "NLP", "GENERATIVE_AI"]
Version = "0.2.4"

[Runtime]
MemoryLimit = "64Gi"
MemoryReservation = "64Gi"
module = "start"
VolumeMount = "/meta_data"
VolumeSize = "100Gi"
ResourceVolumeSize = "64Gi"
GPUCount = 2
RuntimeVersion = "ub2004_cuda114_cudnn8_py38_wlatest_a10g"
RoutingMode = "BASE_URL"
EnableOIDC = true

[[Env]]
Name = "H2O_WAVE_MAX_REQUEST_SIZE"
Value = "20M"

[[Env]]
Name = "HEAP_ID"
Secret = "heap-analytics"
SecretKey = "id"

[[Env]]
Name = "OPENAI_API_KEY"
Secret = "h2o-internal-keys"
SecretKey = "open_ai_key"

[[Env]]
Name = "H2OGPT_URL"
Secret = "h2ogpt-sql-oss-sqlsidekick"
SecretKey = "h2ogpt-url"

[[Env]]
Name = "H2OGPT_API_TOKEN"
Secret = "h2ogpt-sql-oss-sqlsidekick"
SecretKey = "h2ogpt-key"

[[Env]]
Name = "H2OGPTE_URL"
Secret = "h2ogpte-sqlsidekick"
SecretKey = "h2ogpte-url"

[[Env]]
Name = "H2OGPTE_API_TOKEN"
Secret = "h2ogpte-sqlsidekick"
SecretKey = "h2ogpte-key"

[[Env]]
Name = "H2OGPT_BASE_URL"
Secret = "h2ogpt-base-sqlsidekick"
SecretKey = "h2ogpt-base-url"

[[Env]]
Name = "H2OGPT_BASE_API_TOKEN"
Secret = "h2ogpt-base-sqlsidekick"
SecretKey = "h2ogpt-sql-key"
